// Libreria icone per il picker "Nuova categoria", divisa per tipo.
// id = nome icona (chiave di ICON_MAP), label = etichetta mostrata sotto l'icona.
export const CATEGORY_LIBRARY: Record<string, { id: string; label: string }[]> = {
	entrata: [
		{ id: "Briefcase", label: "Stipendio" },
		{ id: "Banknote", label: "Contanti" },
		{ id: "Landmark", label: "Bonifico" },
		{ id: "Award", label: "Bonus" },
		{ id: "Gift", label: "Regalo ricevuto" },
		{ id: "Coins", label: "Extra" },
		{ id: "TrendingUp", label: "Crescita" },
		{ id: "ArrowDownToLine", label: "Incasso" },
		{ id: "HandCoins", label: "Mancia" },
		{ id: "Percent", label: "Interessi" },
		{ id: "Handshake", label: "Freelance" },
		{ id: "CircleDollarSign", label: "Dividendi" },
	],
	spesa: [
		{ id: "ShoppingCart", label: "Spesa quotidiana" },
		{ id: "ShoppingBasket", label: "Alimentari" },
		{ id: "Utensils", label: "Ristoranti" },
		{ id: "Car", label: "Trasporti" },
		{ id: "Home", label: "Casa / Affitto" },
		{ id: "Zap", label: "Utenze" },
		{ id: "Shirt", label: "Abbigliamento" },
		{ id: "HeartPulse", label: "Salute" },
		{ id: "GraduationCap", label: "Formazione" },
		{ id: "Wifi", label: "Internet" },
		{ id: "Fuel", label: "Carburante" },
		{ id: "Baby", label: "Figli" },
		{ id: "PawPrint", label: "Animali" },
		{ id: "Coffee", label: "Bar" },
		{ id: "Wrench", label: "Manutenzione" },
		{ id: "Stethoscope", label: "Visite mediche" },
	],
	investimento: [
		{ id: "TrendingUp", label: "ETF / PAC" },
		{ id: "LineChart", label: "Andamento" },
		{ id: "Landmark", label: "Azioni" },
		{ id: "Bitcoin", label: "Crypto" },
		{ id: "Building2", label: "Immobiliare" },
		{ id: "PieChart", label: "Composizione" },
		{ id: "Layers", label: "Portafoglio" },
		{ id: "Coins", label: "Obbligazioni" },
		{ id: "BarChart3", label: "Rendimento" },
		{ id: "Vault", label: "Deposito" },
		{ id: "Globe", label: "Fondi esteri" },
		{ id: "Percent", label: "Rendimento %" },
	],
	risparmio: [
		{ id: "PiggyBank", label: "Generico" },
		{ id: "Shield", label: "Fondo emergenza" },
		{ id: "Plane", label: "Viaggio" },
		{ id: "Home", label: "Casa nuova" },
		{ id: "GraduationCap", label: "Studi figli" },
		{ id: "Heart", label: "Matrimonio" },
		{ id: "Gem", label: "Grande acquisto" },
		{ id: "Target", label: "Obiettivo" },
		{ id: "Baby", label: "Fondo bebè" },
		{ id: "Car", label: "Auto nuova" },
		{ id: "Umbrella", label: "Protezione" },
		{ id: "Sunrise", label: "Pensione" },
		{ id: "Sparkles", label: "Occasione speciale" },
	],
	abbonamento: [
		{ id: "Repeat", label: "Generico" },
		{ id: "Tv", label: "Streaming" },
		{ id: "Music", label: "Musica" },
		{ id: "Smartphone", label: "Telefonia" },
		{ id: "Cloud", label: "Storage" },
		{ id: "Newspaper", label: "Riviste" },
		{ id: "Dumbbell", label: "Palestra" },
		{ id: "Wifi", label: "Connettività" },
		{ id: "Gamepad2", label: "Cloud gaming" },
		{ id: "BookOpen", label: "Ebook / audiolibri" },
		{ id: "Mail", label: "Posta premium" },
		{ id: "CreditCard", label: "Carta prepagata" },
		{ id: "Radio", label: "Podcast" },
		{ id: "Headphones", label: "Musica premium" },
	],
};
