import type { SeichiIcon } from "./seichi-icons";
import {
	BanknoteIcon,
	BriefcaseIcon,
	AwardIcon,
	GiftIcon,
	ArrowDownLeftIcon,
	ShoppingCartIcon,
	UtensilsCrossedIcon,
	CarIcon,
	HeartPulseIcon,
	ShirtIcon,
	SmileIcon,
	HomeIcon,
	ShieldIcon,
	PlaneIcon,
	Building2Icon,
	LaptopIcon,
	BarChart2Icon,
	TrendingUpIcon,
	BitcoinIcon,
	PiggyBankIcon,
	PlayIcon,
	MusicIcon,
	DumbbellIcon,
	ZapIcon,
	KeyRoundIcon,
} from "./seichi-icons";

export const ICON_MAP: Record<string, SeichiIcon> = {
	Banknote: BanknoteIcon,
	Briefcase: BriefcaseIcon,
	Award: AwardIcon,
	Gift: GiftIcon,
	ArrowDownLeft: ArrowDownLeftIcon,
	ShoppingCart: ShoppingCartIcon,
	UtensilsCrossed: UtensilsCrossedIcon,
	Car: CarIcon,
	HeartPulse: HeartPulseIcon,
	Shirt: ShirtIcon,
	Smile: SmileIcon,
	Home: HomeIcon,
	Shield: ShieldIcon,
	Plane: PlaneIcon,
	Building2: Building2Icon,
	Laptop: LaptopIcon,
	BarChart2: BarChart2Icon,
	TrendingUp: TrendingUpIcon,
	Bitcoin: BitcoinIcon,
	PiggyBank: PiggyBankIcon,
	Play: PlayIcon,
	Music: MusicIcon,
	Dumbbell: DumbbellIcon,
	Zap: ZapIcon,
	KeyRound: KeyRoundIcon,
};
