import type { SeichiIcon } from "./seichi-icons";
import {
	ArrowDownLeftIcon,
	ArrowDownToLineIcon,
	AwardIcon,
	BabyIcon,
	BanknoteIcon,
	BarChart2Icon,
	BarChart3Icon,
	BitcoinIcon,
	BookOpenIcon,
	BriefcaseIcon,
	Building2Icon,
	CarIcon,
	CircleDollarSignIcon,
	CloudIcon,
	CoffeeIcon,
	CoinsIcon,
	CreditCardIcon,
	DumbbellIcon,
	FuelIcon,
	Gamepad2Icon,
	GemIcon,
	GiftIcon,
	GlobeIcon,
	GraduationCapIcon,
	HandCoinsIcon,
	HandshakeIcon,
	HeadphonesIcon,
	HeartIcon,
	HeartPulseIcon,
	HomeIcon,
	KeyRoundIcon,
	LandmarkIcon,
	LaptopIcon,
	LayersIcon,
	LineChartIcon,
	MailIcon,
	MusicIcon,
	NewspaperIcon,
	PawPrintIcon,
	PercentIcon,
	PieChartIcon,
	PiggyBankIcon,
	PlaneIcon,
	PlayIcon,
	RadioIcon,
	RepeatIcon,
	ShieldIcon,
	ShirtIcon,
	ShoppingBasketIcon,
	ShoppingCartIcon,
	SmartphoneIcon,
	SmileIcon,
	SparklesIcon,
	StethoscopeIcon,
	SunriseIcon,
	TargetIcon,
	TrendingUpIcon,
	TvIcon,
	UmbrellaIcon,
	UtensilsIcon,
	UtensilsCrossedIcon,
	VaultIcon,
	WifiIcon,
	WrenchIcon,
	ZapIcon,
} from "./seichi-icons";

export const ICON_MAP: Record<string, SeichiIcon> = {
	ArrowDownLeft: ArrowDownLeftIcon,
	ArrowDownToLine: ArrowDownToLineIcon,
	Award: AwardIcon,
	Baby: BabyIcon,
	Banknote: BanknoteIcon,
	BarChart2: BarChart2Icon,
	BarChart3: BarChart3Icon,
	Bitcoin: BitcoinIcon,
	BookOpen: BookOpenIcon,
	Briefcase: BriefcaseIcon,
	Building2: Building2Icon,
	Car: CarIcon,
	CircleDollarSign: CircleDollarSignIcon,
	Cloud: CloudIcon,
	Coffee: CoffeeIcon,
	Coins: CoinsIcon,
	CreditCard: CreditCardIcon,
	Dumbbell: DumbbellIcon,
	Fuel: FuelIcon,
	Gamepad2: Gamepad2Icon,
	Gem: GemIcon,
	Gift: GiftIcon,
	Globe: GlobeIcon,
	GraduationCap: GraduationCapIcon,
	HandCoins: HandCoinsIcon,
	Handshake: HandshakeIcon,
	Headphones: HeadphonesIcon,
	Heart: HeartIcon,
	HeartPulse: HeartPulseIcon,
	Home: HomeIcon,
	KeyRound: KeyRoundIcon,
	Landmark: LandmarkIcon,
	Laptop: LaptopIcon,
	Layers: LayersIcon,
	LineChart: LineChartIcon,
	Mail: MailIcon,
	Music: MusicIcon,
	Newspaper: NewspaperIcon,
	PawPrint: PawPrintIcon,
	Percent: PercentIcon,
	PieChart: PieChartIcon,
	PiggyBank: PiggyBankIcon,
	Plane: PlaneIcon,
	Play: PlayIcon,
	Radio: RadioIcon,
	Repeat: RepeatIcon,
	Shield: ShieldIcon,
	Shirt: ShirtIcon,
	ShoppingBasket: ShoppingBasketIcon,
	ShoppingCart: ShoppingCartIcon,
	Smartphone: SmartphoneIcon,
	Smile: SmileIcon,
	Sparkles: SparklesIcon,
	Stethoscope: StethoscopeIcon,
	Sunrise: SunriseIcon,
	Target: TargetIcon,
	TrendingUp: TrendingUpIcon,
	Tv: TvIcon,
	Umbrella: UmbrellaIcon,
	Utensils: UtensilsIcon,
	UtensilsCrossed: UtensilsCrossedIcon,
	Vault: VaultIcon,
	Wifi: WifiIcon,
	Wrench: WrenchIcon,
	Zap: ZapIcon,
};
